### ISSUE TITLE
What tensorflow versions are possible?

### ISSUE THREAD

**Issue by lambdaofgod** [google-research/bleurt#59]
I am trying to run bleurt with tensorflow 2.15 and I get 

```
TypeError: Binding inputs to tf.function failed due to `got an unexpected keyword argument 'input_ids'`. Received args: () and kwargs: {'input_ids': <tf.Tensor: shape=(10, 128), dtype=int64, numpy=
```

Which looks like my tensorflow is too new.

What is the newest tensorflow version supported by bleurt?

**Comment by DaekyooKim** [comment]
In my case, it works with version 2.13.1

**Comment by deepvine** [comment]
In my case, it worked with version 2.13.1
